"""End-to-end walk-through of the AgentMart web frontend against the local mock API.

Run:  node server.js &  (in web-mock)   and   python3 -m http.server 8080 (in web)
      PLAYWRIGHT_BROWSERS_PATH=/opt/pw-browsers python3 e2e.py
"""
import os, re, sys, json
from playwright.sync_api import sync_playwright, expect

WEB = os.environ.get("WEB", "http://localhost:8080")
API = os.environ.get("API", "http://localhost:8787")
SHOTS = os.environ.get("SHOTS", "/home/claude/platform/shots")
U = lambda h="": f"{WEB}/?api={API}#/{h}"
os.makedirs(SHOTS, exist_ok=True)

errors, failures = [], []
def check(cond, msg):
    print(("  ok  " if cond else "  FAIL ") + msg)
    if not cond: failures.append(msg)

def attach(page, label):
    page.on("console", lambda m: errors.append(f"[{label}] console.{m.type}: {m.text} @ {m.location.get('url','')}") if m.type in ("error", "warning") else None)
    page.on("pageerror", lambda e: errors.append(f"[{label}] pageerror: {e}"))

def shot(page, name, full=True):
    page.wait_for_timeout(350)
    page.screenshot(path=f"{SHOTS}/web-{name}.png", full_page=full)

def no_hscroll(page, where):
    sw = page.evaluate("document.documentElement.scrollWidth"); cw = page.evaluate("document.documentElement.clientWidth")
    check(sw <= cw + 1, f"no horizontal scroll on {where} ({sw} <= {cw})")

DEV_WORDS = re.compile(r"\b(test|tests|testing|demo|mock|sample|placeholder|prototype|todo)\b", re.I)
def no_dev_words(page, where):
    txt = page.inner_text("body")
    hits = sorted(set(m.group(0) for m in DEV_WORDS.finditer(txt)))
    check(not hits, f"no dev/test wording visible on {where} {hits}")

def shot_launch(page, name, full=True):
    page.wait_for_timeout(350)
    page.screenshot(path=f"{SHOTS}/launch-{name}.png", full_page=full)

def register(page, name):
    page.goto(U("console")); page.wait_for_selector("#regForm")
    page.fill("#rName", name)
    page.fill("#rDesc", f"{name} automation agent")
    page.fill("#rEmail", f"{name}@example.com")
    page.click("#regForm button[type=submit]")
    page.wait_for_selector(".secret .key code")
    key = page.inner_text(".secret .key code").strip()
    check(key.startswith("am_live_"), f"register {name}: api_key shown once ({key[:14]}…)")
    return key

def continue_after_reg(page):
    page.check("#storedKey"); page.click("#regContinue")
    page.wait_for_selector(".con-tabs")

def signout(page):
    page.goto(U("console/settings")); page.wait_for_selector("#profileForm")
    page.click("#conBody [data-signout]"); page.click("#dlg button[value=ok]")
    page.wait_for_selector("#signinForm")

def signin(page, key):
    page.goto(U("console")); page.wait_for_selector("#signinForm")
    page.fill("#sKey", key); page.click("#signinForm button[type=submit]")
    page.wait_for_selector(".con-tabs")

def deposit(page, dollars):
    page.goto(U("console/wallet")); page.wait_for_selector("#depositForm")
    page.fill("#depAmt", str(dollars)); page.click("#depositForm button[type=submit]")
    page.wait_for_function(f"document.querySelector('.kpi.hl .val') && document.querySelector('.kpi.hl .val').textContent.includes('{dollars}')")
    page.wait_for_selector("#txBox table")

with sync_playwright() as p:
    b = p.chromium.launch()
    ctx = b.new_context(viewport={"width": 1440, "height": 900})
    page = ctx.new_page(); attach(page, "desktop")

    print("HOME")
    page.goto(U("")); page.wait_for_selector("#homeStats .stat .val:not(:has(.skel))")
    page.wait_for_selector("#freshGrid .pcard")
    check(page.locator("#homeStats .stat").count() == 5, "5 live stats tiles")
    check("sandbox" in page.inner_text(".topbar").lower(), "sandbox banner visible")
    check("© 2026 AgentMart · A Galaxor AI venture" in page.inner_text("footer"), "footer copyright")
    check(page.inner_text(".topbar").strip() == "Public beta · Orders settle in sandbox credits while live payments roll out.", "beta banner copy")
    foot = page.inner_text("footer")
    check(all(x in foot for x in ["hello@agentmart.us", "support@agentmart.us", "shanto@agentmart.us"]), "footer contact emails")
    check(page.locator("footer a[href='mailto:support@agentmart.us']").count() == 1, "footer mailto links")
    check(page.locator("#contact .contact-list li").count() == 3, "home contact block")
    check(page.get_attribute("link[rel=canonical]", "href") == "https://agentmart.us/" and page.get_attribute("meta[property='og:url']", "content") == "https://agentmart.us/", "canonical + og:url")
    check("Beta activity" in page.inner_text("#view-home"), "stat strip labeled Beta activity")
    check(page.locator("#freshGrid .example-stk").count() == page.locator("#freshGrid .pcard").count(), "home strip cards labeled Example")
    page.click("#contact [data-copy-text='support@agentmart.us']"); page.wait_for_selector("#toast.show")
    check(True, "contact copy button")
    no_dev_words(page, "home")
    shot(page, "home-desktop")

    print("MARKET")
    page.goto(U("market")); page.wait_for_selector("#grid .pcard")
    page.wait_for_selector("#catChips .chip")
    n = page.locator("#grid .pcard").count(); check(n >= 12, f"market shows {n} live listings (first page)")
    check(page.locator("#grid .rating-line .stars-g").count() >= 5, "star ratings on cards")
    check(page.locator("#grid .example-stk").count() == page.locator("#grid .pcard").count(), "every card carries the Example listing label")
    check("illustrative examples" in page.inner_text("#view-market .beta-notice"), "marketplace beta notice")
    check(page.locator("#grid .pcard h3", has_text="[Demo]").count() == 0 and page.locator("#grid .pcard h3", has_text="Lip Balm Set").count() == 1, "[Demo] prefix stripped from titles")
    no_dev_words(page, "marketplace")
    shot(page, "market-desktop")
    page.fill("#q", "huila"); page.wait_for_function("document.querySelectorAll('#grid .pcard').length === 1")
    check(True, "search huila narrows to 1")
    page.fill("#q", "zzzz-nothing"); page.wait_for_selector("#grid .state")
    check("No listings match" in page.inner_text("#grid"), "empty state")
    page.click("#grid [data-reset]"); page.wait_for_function("document.querySelectorAll('#grid .pcard').length >= 5")
    page.check("#fKind input[value=digital]"); page.wait_for_function("document.querySelectorAll('#grid .pcard').length === 4")
    check("digital" in page.url, "kind filter updates URL")
    page.click("[data-mode=agent]"); page.wait_for_selector("#grid .jcard")
    check("digital_delivery\"" not in page.inner_text("#grid"), "agent JSON never shows digital payload")
    shot(page, "market-json-desktop")
    page.click("[data-mode=human]")
    page.click("#fReset"); page.wait_for_function("document.querySelectorAll('#grid .pcard').length >= 5")
    page.select_option("#fSort", "price_desc"); page.wait_for_timeout(400)
    first = page.inner_text("#grid .pcard .pr >> nth=0"); check(first.startswith("$150"), f"sort price_desc first = {first}")
    # categories + rating filter + rating sort
    page.click("#catChips [data-cat=home-kitchen]"); page.wait_for_function("document.querySelectorAll('#grid .pcard').length === 2")
    check(page.get_attribute("#catChips [data-cat=home-kitchen]", "aria-pressed") == "true", "category chip filters (home-kitchen → 2)")
    page.click("#catChips [data-cat='']"); page.wait_for_timeout(500)
    page.check("#fRating input[value='4.5']"); page.wait_for_function("document.querySelectorAll('#grid .pcard').length === 2")
    check(True, "min_rating 4.5 filter → 2 listings")
    page.check("#fRating input[value='']"); page.select_option("#fSort", "rating"); page.wait_for_timeout(600)
    check("Huila" in page.inner_text("#grid .pcard h3 >> nth=0"), "sort=rating puts the 5.0 listing first")
    page.select_option("#fSort", "relevance")
    page.fill("#fMax", "40"); page.wait_for_timeout(900)
    prices = [float(t.replace("$", "").replace(",", "")) for t in page.locator("#grid .pcard .pr").all_inner_texts()]
    check(prices and max(prices) <= 40, f"max price filter {prices}")
    page.fill("#fMax", ""); page.fill("#fMin", "50"); page.fill("#fMax", "10"); page.wait_for_timeout(700)
    check("higher" in page.inner_text("#priceErr"), "min>max validation")
    page.click("#fReset"); page.wait_for_timeout(500)

    print("LISTING DETAIL")
    page.click("#grid .pcard >> text=Stoneware Pour-Over Mug"); page.wait_for_selector(".pd-info h1")
    check("Stoneware" in page.inner_text(".pd-info h1"), "detail title")
    check(page.locator("#buyPanel >> text=Register or sign in").count() == 1, "buy panel asks to sign in when signed out")
    code = page.inner_text(".pd-sec .code pre")
    check(API in code and "lst_" in code, "curl snippet uses real base + listing id")
    page.wait_for_selector("#revBox .rev")
    check(page.locator("#revBox .rev").count() == 2 and page.locator("#revBox .reply").count() == 1, "listing reviews with seller reply")
    page.select_option("#revSort", "lowest"); page.wait_for_timeout(400)
    check("4/5" in page.inner_text("#revBox .rev >> nth=0"), "review sort lowest")
    check("illustrative examples" in page.inner_text("#listingRoot .beta-notice"), "listing beta notice")
    check(page.inner_text("#buyTitle") == "Try a sandbox purchase with your agent" and "no goods ship" in page.inner_text("#buy"), "buy panel retitled + disclosure")
    check(page.locator(".gallery .example-stk").count() == 1, "listing Example label")
    check("[Demo]" not in page.inner_text(".pd-info"), "[Demo] stripped from description")
    no_dev_words(page, "listing detail")
    shot(page, "listing-desktop")

    print("SELLER: register, deposit, store, listings")
    seller_key = register(page, "seller-bot")
    shot(page, "console-register-secret-desktop", full=False)
    continue_after_reg(page)
    deposit(page, 500)
    shot(page, "console-wallet-desktop")
    page.goto(U("console/store")); page.wait_for_selector("#storeForm")
    page.fill("#stName", "Seller Bot Supply")
    page.keyboard.press("Tab")
    check(page.input_value("#stSlug") == "seller-bot-supply", "slug auto-derived")
    page.fill("#stFrom", "US, Austin TX"); page.fill("#stRet", "30-day returns")
    page.click("#storeForm button[type=submit]"); page.wait_for_selector("#listingForm")
    # validation errors
    page.click("#listingForm button[type=submit]")
    check(page.locator("#listingForm [aria-invalid=true]").count() >= 3, "listing form shows field errors")
    # physical listing
    page.fill("#lfTitle", "Recycled Canvas Tote Bag, 15 L")
    page.fill("#lfDesc", "Heavy 16 oz recycled cotton canvas tote with an inner pocket and reinforced handles. Folds flat, machine washable, built for groceries and laptops.")
    page.fill("#lfPrice", "24.5"); page.fill("#lfInv", "10"); page.fill("#lfCat", "bags"); page.fill("#lfTags", "tote, bag, canvas")
    ins = page.locator("#lfAttrs input")
    for i, v in enumerate(["Material", "Recycled cotton", "Volume", "15 L", "Weight", "380 g"]): ins.nth(i).fill(v)
    page.fill("#lfShip", "5"); page.fill("#lfTo", "US, CA")
    page.wait_for_timeout(600)
    score = int(page.inner_text("#gNum")); check(score >= 90, f"readiness meter live = {score}")
    shot(page, "console-new-listing-desktop")
    page.click("#listingForm button[type=submit]"); page.wait_for_selector(".lrow >> text=Recycled Canvas Tote")
    # digital listing
    page.click("[data-new-listing]"); page.wait_for_selector("#listingForm")
    page.click("[data-lfkind=digital]")
    page.fill("#lfTitle", "Agent Prompt Pack: 50 Procurement Prompts"); page.fill("#lfDesc", "Fifty tested prompts for procurement agents.")
    page.fill("#lfPrice", "9"); page.select_option("#lfDdType", "text"); page.fill("#lfDd", "PROMPTS-DEMO-CONTENT-123")
    page.click("#listingForm button[type=submit]"); page.wait_for_selector(".lrow >> text=Agent Prompt Pack")
    # service listing
    page.click("[data-new-listing]"); page.wait_for_selector("#listingForm")
    page.click("[data-lfkind=service]")
    page.fill("#lfTitle", "Market research brief, 5 days"); page.fill("#lfDesc", "A sourced competitor brief.")
    page.fill("#lfPrice", "120"); page.fill("#lfTurn", "5"); page.fill("#lfDeliv", "PDF report link")
    page.click("#listingForm button[type=submit]"); page.wait_for_selector(".lrow >> text=Market research brief")
    check(page.locator(".lrow").count() == 3, "3 listings in my store")
    # edit + pause/activate
    row = page.locator(".lrow", has_text="Market research brief")
    row.locator("[data-l-edit]").first.click(); page.wait_for_selector("[data-edit-form]")
    page.fill("[data-edit-form] input[name=price]", "150"); page.click("[data-edit-form] button[type=submit]")
    page.wait_for_selector(".lrow >> text=$150.00")
    page.locator(".lrow", has_text="Market research brief").locator("[data-l-status=paused]").click()
    page.wait_for_selector(".lrow:has-text('Market research brief') .badge.st-paused")
    check(True, "edit price + pause listing")
    shot(page, "console-store-desktop")
    tote_id = page.locator(".lrow", has_text="Recycled Canvas Tote").get_attribute("data-lid")
    signout(page)

    print("BUYER: register, deposit, buy digital + physical")
    buyer_key = register(page, "buyer-bot")
    continue_after_reg(page)
    # mandate edit
    page.goto(U("console/overview")); page.wait_for_selector("#mandateForm")
    page.fill("#mMax", "100"); page.fill("#mDaily", "1000"); page.click("#mandateForm button[type=submit]")
    page.wait_for_selector("#toast.show >> text=Mandate saved")
    deposit(page, 200)
    # insufficient mandate check path: buy demo font ($79) digital
    page.goto(U("market")); page.fill("#q", "Pantry"); page.wait_for_function("document.querySelectorAll('#grid .pcard').length === 1")
    page.click("#grid .pcard"); page.wait_for_selector("#buyForm")
    page.click("#buyForm button[type=submit]"); page.wait_for_selector("#buyResult")
    res = page.inner_text("#buyResult")
    check("completed" in res and "DEMO-PANTRY" in res, "digital purchase completes with delivery payload")
    shot(page, "listing-bought-digital-desktop", full=False)
    page.goto(U("listing/" + tote_id)); page.wait_for_selector("#buyForm")
    page.click("#buyForm button[type=submit]")
    check(page.locator("#buyForm [aria-invalid=true]").count() >= 5, "address validation errors")
    page.fill("#ship_name", "Ada Agent"); page.fill("#ship_line1", "1 Market St"); page.fill("#ship_city", "Austin")
    page.fill("#ship_region", "TX"); page.fill("#ship_postal_code", "78701"); page.fill("#ship_country", "us")
    page.click("[data-qty='1']")
    check("$54.00" in page.inner_text("#buyTotals"), "totals: 2 × 24.50 + 5 shipping = $54")
    page.click("#buyForm button[type=submit]"); page.wait_for_selector("#buyResult")
    check("paid" in page.inner_text("#buyResult"), "physical purchase is paid (escrow)")
    shot(page, "listing-bought-physical-desktop", full=False)
    # insufficient funds
    page.goto(U("market")); page.fill("#q", "translation"); page.wait_for_function("document.querySelectorAll('#grid .pcard').length === 1")
    page.click("#grid .pcard"); page.wait_for_selector("#buyForm"); page.fill("#buyQty", "3")
    page.click("#buyForm button[type=submit]"); page.wait_for_selector("#buyForm [data-form-err]:has-text('mandate')")
    check(True, "mandate_exceeded surfaced inline")
    signout(page)

    print("SELLER: fulfill")
    signin(page, seller_key)
    page.goto(U("console/orders")); page.wait_for_selector("#oList")
    page.click("[data-orole=seller]"); page.wait_for_selector(".orow >> text=Recycled Canvas Tote")
    page.click(".orow:has-text('Recycled Canvas Tote') .ohead"); page.wait_for_selector("[data-oact=fulfill]")
    check(page.locator("[data-oact=confirm]").count() == 0, "seller has no confirm button")
    page.click("[data-oact=fulfill]"); page.wait_for_selector("[data-fulfill]")
    page.fill("[data-fulfill] input[name=carrier]", "UPS"); page.fill("[data-fulfill] input[name=tracking_number]", "1Z999AA10123456784")
    page.click("[data-fulfill] button[type=submit]"); page.wait_for_selector(".orow .badge.st-fulfilled")
    check(True, "seller fulfilled with carrier/tracking")
    shot(page, "console-orders-seller-desktop")
    signout(page)

    print("BUYER: confirm")
    signin(page, buyer_key)
    page.goto(U("console/orders")); page.wait_for_selector(".orow >> text=Recycled Canvas Tote")
    page.click(".orow:has-text('Recycled Canvas Tote') .ohead"); page.wait_for_selector("[data-oact=confirm]")
    check(page.locator("[data-oact=dispute]").count() == 1 and page.locator("[data-oact=refund]").count() == 0, "buyer actions valid for fulfilled")
    page.click("[data-oact=confirm]"); page.click("#dlg button[value=ok]")
    page.wait_for_selector(".orow:has-text('Recycled Canvas Tote') .badge.st-completed")
    check(True, "buyer confirmed → completed")
    row = ".orow:has-text('Recycled Canvas Tote')"
    page.wait_for_selector(f"{row} [data-oact=review]")
    page.click(f"{row} [data-oact=review]"); page.wait_for_selector("[data-review-form]")
    page.click("[data-review-form] [type=submit]")
    check("Pick 1 to 5" in page.inner_text("[data-review-form]"), "review needs a rating")
    page.click("[data-review-form] label[for$='_5']"); page.fill("[data-review-form] input[name=title]", "Sturdy tote <b>x</b>")
    page.fill("[data-review-form] textarea[name=body]", "Arrived quickly, stitching is solid.")
    page.click("[data-review-form] [type=submit]"); page.wait_for_selector(f"{row} .rev")
    check("Sturdy tote <b>x</b>" in page.inner_text(f"{row} .rev"), "review published (title escaped)")
    shot(page, "console-orders-buyer-desktop")
    page.click(f"{row} .rev [data-oact=review]"); page.wait_for_selector("[data-review-form]")
    page.click("[data-review-form] label[for$='_4']"); page.click("[data-review-form] [type=submit]")
    page.wait_for_selector(f"{row} .rev:has-text('4/5')"); check(True, "review edited to 4 stars")
    frow = ".orow:has-text('Pantry Grotesk')"
    page.click(f"{frow} .ohead"); page.wait_for_selector(f"{frow} [data-oact=review]")
    page.click(f"{frow} [data-oact=review]"); page.click("[data-review-form] label[for$='_3']"); page.click("[data-review-form] [type=submit]")
    page.wait_for_selector(f"{frow} .rev"); page.click(f"{frow} [data-rev-del]"); page.click("#dlg button[value=ok]")
    page.wait_for_selector(f"{frow} [data-oact=review]"); check(True, "review deleted → can write again")
    page.goto(U("console/events")); page.wait_for_selector("#evList .ev")
    check(page.locator("#evList .ev").count() >= 4, "events feed populated")
    shot(page, "console-events-desktop")
    page.goto(U("console/keys")); page.wait_for_selector("#keyList table")
    page.click("[data-key-new]"); page.wait_for_selector("#keySecret .key code")
    check(page.locator("#keyList tbody tr").count() == 2, "new key created and listed")
    page.click("[data-token]"); page.wait_for_selector("#tokenBox .key code")
    shot(page, "console-keys-desktop")
    page.goto(U("console/settings")); page.wait_for_selector("#hookForm")
    page.fill("#whUrl", "http://insecure.example"); page.click("#hookForm button[type=submit]")
    check(page.locator("#whUrl[aria-invalid=true]").count() == 1, "webhook https validation")
    page.fill("#whUrl", "https://agent.example.com/hook"); page.click("#hookForm button[type=submit]")
    page.wait_for_selector("#whSecret .key code"); check(True, "webhook saved; secret shown once")
    page.goto(U("console/overview")); page.wait_for_selector(".kpis")
    shot(page, "console-overview-desktop")

    page.goto(U("console/settings")); page.wait_for_selector("#profileForm")
    page.fill("#pfEmail", "seller-bot@example.com"); page.click("#profileForm button[type=submit]")
    page.wait_for_selector("#pfEmail[aria-invalid=true]"); check("already uses" in page.inner_text("#profileForm"), "duplicate email → inline 409")
    page.fill("#pfEmail", "buyer-2@example.com"); page.click("#profileForm button[type=submit]"); page.wait_for_selector("#toast.show >> text=Profile saved")

    print("SELLER: reply to review, withdraw, payment methods")
    signout(page); signin(page, seller_key)
    page.goto(U("console/store")); page.wait_for_selector("#myRevBox .rev")
    check(page.locator(".lrow .badge.st-paused").count() == 1, "stores/me includes paused listing")
    page.click("#myRevBox [data-reply]"); page.fill("[data-reply-form] textarea", "Thanks! Glad the tote held up.")
    page.click("[data-reply-form] [type=submit]"); page.wait_for_selector("#myRevBox .reply")
    check("Glad the tote" in page.inner_text("#myRevBox .reply"), "seller replied")
    shot(page, "console-store-reviews-desktop")
    page.goto(U("console/wallet")); page.wait_for_selector("#txBox table")
    check(page.locator("#txBox td .badge").count() >= 2, "ledger shows account column")
    page.fill("#wdAmt", "10"); page.click("#withdrawForm button[type=submit]"); page.click("#dlg button[value=ok]")
    page.wait_for_selector("#toast.show >> text=Withdrew $10.00"); check(True, "withdraw sandbox credits")
    page.click("[data-pm-check]"); page.wait_for_function("document.querySelector('#pmResult').textContent.includes('On the roadmap')")
    check(True, "payment-methods 501 surfaced")
    shot(page, "console-wallet-desktop")
    page.goto(U("listing/" + tote_id)); page.wait_for_selector("#revBox .reply")
    check("Glad the tote" in page.inner_text("#revBox"), "public listing shows review + reply")

    print("STORE PAGE + DEVELOPERS")
    page.goto(U("store/seller-bot-supply")); page.wait_for_selector("#storeRoot h1")
    check("Seller Bot Supply" in page.inner_text("#storeRoot h1"), "store page")
    check("illustrative examples" in page.inner_text("#storeRoot .beta-notice"), "store beta notice")
    no_dev_words(page, "store page")
    page.wait_for_selector("#srevBox .rev"); check(page.locator("#storeRoot .rating-line .stars-g").count() >= 1, "store rating + reviews")
    shot(page, "store-desktop")
    page.goto(U("store/does-not-exist")); page.wait_for_selector("#storeRoot .state")
    page.goto(U("listing/lst_nope")); page.wait_for_selector("#listingRoot .state")
    check("isn't on the shelves" in page.inner_text("#listingRoot"), "listing 404 state")
    page.goto(U("developers")); page.wait_for_selector("#refBody .ep-row")
    check("Generated live" in page.inner_text("#refSource"), "endpoint reference generated from openapi.json")
    check(API + "/mcp" in page.inner_text("#devRoot"), "MCP endpoint shown")
    check(page.locator("#dev-contact .contact-list li").count() == 3, "developers contact block")
    no_dev_words(page, "developers")
    dev = page.inner_text("#devRoot")
    check("browse_catalog" in dev and "write_review" in dev and "/v1/catalog" in dev and "/v1/categories" in dev, "developers page lists catalog/categories/reviews + new MCP tools")
    shot(page, "developers-desktop")
    page.goto(U("")); page.wait_for_selector("#freshGrid .pcard"); shot_launch(page, "home-desktop")
    page.goto(U("market")); page.wait_for_selector("#grid .pcard"); page.click("#fReset"); page.wait_for_function("document.querySelectorAll('#grid .pcard').length >= 12"); page.evaluate("window.scrollTo(0,0)"); shot_launch(page, "market-desktop", full=False)
    page.goto(U("listing/" + tote_id)); page.wait_for_selector("#revBox"); shot_launch(page, "listing-desktop")
    page.goto(U("developers")); page.wait_for_selector("#dev-contact"); page.locator("#dev-contact").scroll_into_view_if_needed(); shot_launch(page, "developers-contact-desktop", full=False)
    page.goto(U("nowhere")); page.wait_for_selector("#view-notfound.active")

    # XSS probe: listing title with markup must render as text
    print("XSS")
    xss_title = '<img src=x onerror="window.__xss=1">Evil <b>bold</b>'
    signout(page); signin(page, seller_key)
    r = page.evaluate("""async ([api, key, t]) => { const r = await fetch(api + '/v1/listings', {method:'POST', headers:{'Content-Type':'application/json', Authorization:'Bearer '+key}, body: JSON.stringify({title:t, description:'<script>window.__xss=2</script>', kind:'digital', price_cents:100, digital_delivery:{type:'text', payload:'<svg onload=window.__xss=3>'}})}); return r.json(); }""", [API, seller_key, xss_title])
    page.goto(U("market")); page.wait_for_selector("#grid .pcard")
    page.goto(U("listing/" + r["id"])); page.wait_for_selector(".pd-info h1")
    check(page.inner_text(".pd-info h1") == xss_title, "hostile title rendered as text")
    check(page.evaluate("window.__xss") is None, "no script execution from listing content")
    signout(page)

    print("MOBILE 390")
    m = b.new_context(viewport={"width": 390, "height": 844}, device_scale_factor=2, is_mobile=True, has_touch=True)
    mp = m.new_page(); attach(mp, "mobile")
    for name, h, sel in [("home", "", "#homeCats .chip"), ("market", "market", "#grid .pcard"), ("listing", "listing/" + tote_id, ".pd-info h1"), ("console-auth", "console", "#regForm"), ("developers", "developers", "#refBody .ep-row"), ("store", "store/seller-bot-supply", "#storeRoot h1")]:
        mp.goto(U(h)); mp.wait_for_selector(sel); no_hscroll(mp, "mobile " + name); shot(mp, name + "-mobile")
    mp.goto(U("console")); mp.wait_for_selector("#signinForm")
    mp.fill("#sKey", buyer_key); mp.click("#signinForm button[type=submit]"); mp.wait_for_selector(".con-tabs")
    for name, h, sel in [("console-overview", "console/overview", "#mandateForm"), ("console-wallet", "console/wallet", "#txBox table"), ("console-orders", "console/orders", ".orow")]:
        mp.goto(U(h)); mp.wait_for_selector(sel); no_hscroll(mp, "mobile " + name); shot(mp, name + "-mobile")
    mp.click(".orow .ohead >> nth=0"); mp.wait_for_selector(".obody"); no_hscroll(mp, "mobile order detail"); shot(mp, "console-order-open-mobile")
    for name, h, sel in [("home", "", "#homeStats .stat .val:not(:has(.skel))"), ("market", "market", "#grid .pcard"), ("listing", "listing/" + tote_id, "#revBox"), ("contact", "home/contact", "#contact")]:
        mp.goto(U(h)); mp.wait_for_selector(sel)
        if name == "contact":
            mp.wait_for_timeout(800); mp.locator("#contact .contact-card").screenshot(path=f"{SHOTS}/launch-contact-mobile.png")
        else:
            shot_launch(mp, name + "-mobile")
    mp.goto(U("")); mp.click("#menuBtn"); mp.wait_for_selector("#mobileMenu.open"); shot(mp, "menu-mobile", full=False)

    # tablet sanity
    t = b.new_context(viewport={"width": 820, "height": 1100}); tp = t.new_page(); attach(tp, "tablet")
    for h, sel in [("", "#freshGrid .pcard"), ("market", "#grid .pcard"), ("developers", "#refBody .ep-row")]:
        tp.goto(U(h)); tp.wait_for_selector(sel); no_hscroll(tp, "tablet " + (h or "home"))
    tp.goto(U("")); tp.wait_for_selector("#freshGrid .pcard"); shot(tp, "home-tablet")

    # live-mode wallet (mock started with LIVE=1 on :8788)
    print("LIVE MODE")
    LAPI = API.replace("8787", "8788")
    lc = b.new_context(viewport={"width": 1280, "height": 900}); lp = lc.new_page(); attach(lp, "live")
    lp.goto(f"{WEB}/?api={LAPI}#/console"); lp.wait_for_selector("#regForm")
    lp.fill("#rName", "live-bot"); lp.click("#regForm button[type=submit]"); lp.wait_for_selector("#storedKey")
    lp.check("#storedKey"); lp.click("#regContinue"); lp.wait_for_selector("#depositForm")
    check("live" in lp.inner_text("#depTitle"), "wallet shows mode live")
    lp.fill("#depAmt", "25"); lp.click("#depositForm button[type=submit]"); lp.wait_for_selector("#checkoutBox a[href^='https://checkout.stripe.com']")
    check(True, "live deposit opens checkout_url")
    check(lp.locator("#withdrawForm button[type=submit][disabled]").count() == 1, "live withdraw disabled (needs Stripe Connect)")
    shot(lp, "console-wallet-live-desktop", full=False)
    for extra in lc.pages[1:]: extra.close()

    # offline API → error states
    print("ERROR STATES")
    e = b.new_context(viewport={"width": 1280, "height": 900}); ep = e.new_page()
    ep.goto(f"{WEB}/?api=http://localhost:9#/market"); ep.wait_for_selector("#grid .state.err")
    check("Can't reach" in ep.inner_text("#grid"), "network error state in market")
    shot(ep, "market-error-desktop", full=False)
    b.close()

# errors: ignore the deliberate network failures of the error-state context (not attached)
EXPECTED = ("fonts.googleapis.com",            # sandbox proxy blocks Google Fonts
            "status of 409 (Conflict) @ " + API + "/v1/me",   # deliberate duplicate-email test
            "status of 501 (Not Implemented) @ " + API + "/v1/wallet/payment-methods",  # deliberate 501 probe
            "403 (Forbidden) @ " + API + "/v1/orders",   # deliberate mandate_exceeded test
            API + "/v1/stores/does-not-exist", API + "/v1/listings/lst_nope")  # deliberate 404 tests
real = [x for x in errors if not any(e in x for e in EXPECTED)]
print("\nCONSOLE/PAGE ERRORS:", len(real))
for x in real: print("  ", x)
print("FAILURES:", len(failures))
for f in failures: print("  ", f)
sys.exit(1 if failures or real else 0)
